Metadata changes
fairdataihub/SODA-for-SPARC pull request #91
Opened 2022-05-12 19:35 UTC by slugb0t

update on the metadata tab layout (create manifest has same icon as the other as well and readme has been moved to top row)
Also in step 4 of preparing a dataset README is going to be a mandatory metadata file

2022-05-20 15:59 UTC, aaronm-2112 requested changes
In step 4 when being told 
"You did not include the following metadata files that are typically expected for all SPARC datasets: "

it lists out required metadata files that I did include. Based off the warning message text, I would expect this list to only show me the required metadata files I failed to include.

2022-05-20 23:29 UTC, bvhpatel commented
@aaronm-2112 @slugb0t Should we just change it to "You did not include some of the following metadata files that are typically expected for all SPARC datasets: "?

2022-06-01 16:07 UTC, aaronm-2112 approved these changes

2022-06-01 20:51 UTC, slugb0t commented
Previously in step 4, the metadata check listed all required files even if included. Now will only show ones that are missing.

2022-06-03 15:51 UTC, merged